# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{outlook_importer}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Frank Pr\303\266\303\237dorf, Thilo Utke"]
  s.date = %q{2010-10-25}
  s.description = %q{Nothing more to say}
  s.email = %q{dont@bother.me}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "VERSION",
     "outlook_importer.gemspec",
     "outlook_importer.rb",
     "test/livemail_de.csv",
     "test/outlook_2007_de.csv",
     "test/outlook_importer_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/thilo/outlook_importer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple importer for outlook and alike csv files}
  s.test_files = [
    "test/outlook_importer_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fastercsv>, [">= 1.5.0"])
      s.add_development_dependency(%q<test-unit>, [">= 1.2.3"])
    else
      s.add_dependency(%q<fastercsv>, [">= 1.5.0"])
      s.add_dependency(%q<test-unit>, [">= 1.2.3"])
    end
  else
    s.add_dependency(%q<fastercsv>, [">= 1.5.0"])
    s.add_dependency(%q<test-unit>, [">= 1.2.3"])
  end
end

